### ISSUE TITLE
Windows 11 insider beta (22623.1037) Menu not aligning to Taskbar correctly

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#1261]
**Describe the bug**
On the beta Insider version, the Start menu is detached from the Taskbar. This is without changing the position offset.

**Expected behavior**
The menu should be attached to the Taskbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/61938331/209474702-2b53ce42-ed8c-4a5c-a813-4da1b319bc11.png)

**Version:**
 - Open-Shell: 4.4.184
 - OS: Windows 11 build 22623.1037

**Additional context**
If it may make a difference, I am using a device with 200% scaling, however when I set the DPI override to 96, the issue persists.

**Comment by ge0rdi** [comment]
Will you provide a log obtained using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)?
It should contain information about menu positioning.

**Comment by bonzibudd** [comment]
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/10300590/StartMenuLog.txt)

And apologies, I forgot that I'm actually using [this](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/45769362) testing build, if that may make a difference. Enabling "Align start menu to working area" actually restores expected behavior, but it's disabled by default.

**Comment by ge0rdi** [comment]
If you changed system display scaling, could you logoff and logon again (to make sure everything is recomputed  correctly)?
According to log your taskbar is supposed to be 144px high, but it has 96px on the picture.
The start menu is aligned to supposed taskbar top.

> And apologies, I forgot that I'm actually using [this](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/45769362) testing build, if that may make a difference.

Ideally you should check if the observed behavior is present in normal builds as well. In such case generic issue report is appropriate.
Otherwise the report should go to given PR (as the issue may be related to PR changes).

**Comment by bonzibudd** [comment]
Just confirmed that it still applies on 4.4.184, and logging off/on doesn't fix the issue.

Although, I think I may have found the source of the problem, as Windows 11 has an enlarged version of the taskbar when the keyboard is disconnected from the system (I am on a Surface Pro 8). When that is enabled, that increased height is correct. Here's the enlarged taskbar (still at 200% scaling):
![image](https://user-images.githubusercontent.com/61938331/209482270-bec5c99d-7152-452a-a054-77b54d218aa3.png)
It's impossible for me to show this with the menu because it cannot be accessed via touch screen, but the height appears to be correct.

**Comment by bonzibudd** [comment]
![image](https://user-images.githubusercontent.com/61938331/212499461-c0e2b259-0ceb-49a3-b1d9-33a404dc9551.png)

Just noticed that it's also incorrect with the custom button.
Also, the Align to working area option does work correct for the menu in desktop mode, but when the bigger touch UI is enabled, it becomes too low.

**Comment by ge0rdi** [comment]
> Just noticed that it's also incorrect with the custom button.

Yup. That is the consequence of _incorrect_ taskbar size we get. The button is positioned to center of taskbar and since taskbar in your case is smaller than reported start button is shifted.

There is a _region_ set for the part of taskbar window than corresponds to its visible part (`Taskbar Region:` in log). And we are doing some adjustments when the region is present (it is not present always and I don't know what actually triggers the region). But I guess it is just not enough :(

> Also, the Align to working area option does work correct for the menu in desktop mode, but when the bigger touch UI is enabled, it becomes too low.

Could you also provide log obtained with that option (`Align to working area`) enabled?

> when the bigger touch UI is enabled

Do you know about any way to enable such touch UI on standard desktop?
Maybe then I'd be able to reproduce and debug it.

**Comment by bonzibudd** [comment]
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/10420974/StartMenuLog.txt)

It might be possible to enable the touch UI by simply disconnecting the keyboard, but I think it may require an actual touch screen.

However I did find [this](https://stackoverflow.com/questions/40274660/windows-10-how-do-i-test-touch-events-without-a-touchscreen) post. Apparently VS19 has some sort of touch emulator, maybe that will help in some way.

**Comment by ge0rdi** [comment]
This is related to #1744.
Should be fixed in `4.4.194`.

**Comment by dust0vich** [comment]
![Screenshot (2) crop](https://github.com/user-attachments/assets/79e8d7e2-b40d-4e75-8091-6569cd523d13)
Related with the custom button pictured above is when the larger size touch taskbar is shrunk down the button doesn't dissepear. It is perfectly tolerable but obviously not tolerable. This is with the latest release you posted in #1744 .

**Comment by bonzibudd2** [comment]
@ge0rdi I can confirm the issue is fixed. Feel free to close (I can't access my old account anymore due to a 2FA problem)

**Comment by dust0vich** [comment]
> [@ge0rdi](https://github.com/ge0rdi) I can confirm the issue is fixed. Feel free to close (I can't access my old account anymore due to a 2FA problem)

Which version are you using? I am running 4.4.196 Win11 25H2 and still have issues with this.

WIth keyboard attached:
<img width="579" height="221" alt="Image" src="https://github.com/user-attachments/assets/2bcf747c-6c56-43e8-a85e-f1544e201d3e" />

With keyboard detached:

<img width="492" height="198" alt="Image" src="https://github.com/user-attachments/assets/ccab1d99-2019-4106-be85-755461f02933" />

**Comment by bonzibudd2** [comment]
@dust0vich I didn't test for the button. I also have that issue when using a custom button. That wasn't the original focus of this issue but we can use this issue just for the button now.

I feel like this could be fixed by using the same method to align the button as is being used now for the menu. I think we always want it to be in the middle of the taskbar height-wise at least on Windows 11

**Comment by dust0vich** [comment]
Ya custom button is the only way it can work with touch I believe. I did just test the start menu height and yes, it is perfect in both keyboard/no keyboard mode. Hopefully this strategy can work for the button.

**Comment by Patches08** [comment]
Could you guys add permissions and I'll give your guys tools an upgrade at the forks. Just need some corrections whenever necessary. But honestly I'm completely locked out of my GitHub accounts, just on the thread.On Dec 29, 2025 9:04 PM, dust0vich ***@***.***> wrote:dust0vich left a comment (Open-Shell/Open-Shell-Menu#1261)
Ya custom button is the only way it can work with touch I believe. I did just test the start menu height and yes, it is perfect in both keyboard/no keyboard mode. Hopefully this strategy can work for the button.
