### ISSUE TITLE
Missaligned start button and start menu

### ISSUE THREAD

**Issue by ch3mn3y** [Open-Shell/Open-Shell-Menu#1744]
### Describe the bug

Freshky installed Open Shell 4.4.191 on freshky installed Win 11 Insider Canary (25977.1000) and both the button and whole menu arę missaligned about 5 pixels abive their desired position - orbs I use are missaligned about 4-5 pixels.

No problem on other devices that have Win11 (also Canary) and OS for longer.

![openshell](https://github.com/Open-Shell/Open-Shell-Menu/assets/20260224/5fc3cbe7-a6db-4c90-8466-ad0ffce883d6)

### Area of issue

Start menu

### To reproduce

Install and launch

### Expected behavior

Button should be alligned correctly, menu as well

### Open-Shell version

4.4.191

### Windows version

Windows 11 Insider Canary 25977.1000

### Additional context

Device is HP Pavilion X360 14-ba104nw. It's convertibek with touchscreen, but it shiukdn't be a problem - Windows UI  is the same.

**Comment by ge0rdi** [comment]
Just installed latest Win11 insider and everything seems to be _normal_.

What is your display scaling? (`Windows settings` -> `System` -> `Display` -> `Scale`)
Do you have some custom value in `Override system DPI` setting in `Open-Shell settings`?

Does the issue persist also after reboot?

**Comment by ch3mn3y** [comment]
System display scale is set to 125%, not sure about OS one, as I didn't change what was default. Will check in a moment.

Yes, it persist rebooting and reinstalling.

**Comment by ge0rdi** [comment]
Hmm, also with 125% scaling it looks good on my VM.

Can you provide your `Open-Shell` settings XML?

**Comment by ge0rdi** [comment]
I'm sorry but I still cannot replicate such behavior :(

Do you use some other customization software?

**Comment by ch3mn3y** [comment]
None. Only what Windows allows (align left, dark mode, etc)

**Comment by Philaupatte** [comment]
Hi, recently upgrade open shell to 4.4.191 selecting all package and it changes behavior regarding start button. Now it is following windows setting that says "Center".
Went back to 4.4.170 to recover and it works as before.
Windows task bar center and open shell start button to left corner, as I like it. 
![Capture d'écran 2023-10-26 081939](https://github.com/Open-Shell/Open-Shell-Menu/assets/75701874/239dcc3f-6811-433e-825f-8cd07da2037e)

**Comment by ch3mn3y** [comment]
With my bug I just "broke" my orbs, so it's lower (still not in the ideal position, as I can click original Windows button) and used Vertical position setting to move the menu start and it looks decent.

**Comment by mike26037** [comment]
Hello, I'm also having this issue. 
![Screenshot 2023-10-26 004527](https://github.com/Open-Shell/Open-Shell-Menu/assets/149049580/6a296df9-f487-4c23-8bcb-3782b43293ea)

**Comment by ge0rdi** [comment]
@mike26037 
Is it on latest Win11 Insider?
Do you have machine with touch screen?
Is also start menu _shifted_ up?

Guys, can you eventually attach `Open-Shell` [log](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)?
It should contain some info on start button/menu positioning.

**Comment by ch3mn3y** [comment]
> @mike26037 Is it on latest Win11 Insider? Do you have machine with touch screen? Is also start menu _shifted_ up?
> 
> Guys, can you eventually attach `Open-Shell` [log](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)? It should contain some info on start button/menu positioning.

0xfff? With hexadecimal I can 0fff, but it's fff, is that ok? In the end its 0x0000fff (4095)

**Comment by mike26037** [comment]
> @mike26037 Is it on latest Win11 Insider? Do you have machine with touch screen? Is also start menu _shifted_ up?
> 
> Guys, can you eventually attach `Open-Shell` [log](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log)? It should contain some info on start button/menu positioning.

I am on windows 11 home. Touchscreen Dell Inspiron, and yes you can see in my screenshot it is shifted up. here's the log.
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/13183289/StartMenuLog.txt)

**Comment by mhherrUSA** [comment]
Wish I had known of this BUG before I "updated" to 4.4.191 . . . the update SUCKS.  Can't use the "Classic" START BUTTON at all without obscuring items on the taskbar because it only positions the button at the left end of the taskbar instead of the selected "Align with corner of screen" (failing to change to the custom button setting positions the Classic start button directly on top of the leftmost 1 or 2 taskbar icons).  

I detest when developers monkey around with good programs and turn them into crap.  Was there any loud clamor for making all the changes? Where is a USER MANUAL that explains how to overcome the new update failures?

**Comment by Philaupatte** [comment]
Hola, takes it easy. No need to bark. It's true that new design is not clever but developper's will take "returns from us" in their bag. I suggest to get back on version 4.4.170 as I did.
Developper's please read backlog to take in account user's feed back. New design is not usable. Real need to have more options to decide where to place start button whatsoever values of Windows task bar options 
Thanks.

**Comment by ge0rdi** [comment]
It seems the issue is related to touch screen devices.

I was able to replicate it on my Win11 23H2 VM using this guide (Option Three):
https://www.elevenforum.com/t/turn-on-or-off-tablet-optimized-taskbar-in-windows-11.5133/

It is also much worse when `Optimize taskbar for touch interactions when this device is used as a tablet` is enabled.
In such case taskbar _shrinks_ (when not used) but `Open-Shell`'s custom button stays visible all the time.

**Comment by ge0rdi** [comment]
Following `.reg` file can be used to enable touch-optimized taskbar (to replicate the issue):
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
"TabletPostureTaskbar"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ExpandableTaskbar"=dword:00000000
```

**Comment by ge0rdi** [comment]
Could you, please, test with this PR build?
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/49215189/artifacts

It should fix the issue.

**Comment by dust0vich** [comment]
Hello,
Just upgraded to windows 11 and have this issue. Is there any way to get a copy of the PR build as the artifacts are deleted after one month.

**Comment by ge0rdi** [comment]
Here is fresh build:
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/51014494/artifacts

**Comment by Amenel** [comment]
This is to report that the misalignment is no longer an issue, after I installed Open Shell 4.4.194 yesterday. I noticed the button is now correctly placed as soon as the installation was finished. Note that I had updated Windows 11 to version 24H2 the day before. I too have a touch-enabled laptop, a Dell Inspiron 7620 2-in-1.

I'd like to thank @ge0rdi and the contributors for making this possible, and for their continued work on this. As the maintainer of two open source projects, I know what this might involve. I'm thankful for your dedication.

**Comment by Erich-0** [comment]
Sorry, my HP x360-G2 on Windows 11 24H2 with touchscreen still experiences the issue after installing Open Schell 4.4.194.

**Comment by Amenel** [comment]
Sorry that it did not align correctly for you. It was such an intense moment of joy, even though it was brief. Hopefully, a future version solves it also in your case.

**Comment by dust0vich** [comment]
![Screenshot (2) crop](https://github.com/user-attachments/assets/79e8d7e2-b40d-4e75-8091-6569cd523d13
![Screenshot (3) crop](https://github.com/user-attachments/assets/da049c04-6baa-447e-9d7a-37de3644ca1f)

Related with the custom button pictured above is when the larger size touch taskbar is shrunk down the button doesn't dissepear. It is perfectly tolerable but obviously not optimal. Also the larger touch optimized taskbar the icon is in the correct place but the icon is not scaled appropriately.

**Comment by Amenel** [comment]
Well, I updated to 4.4.195 today and just as immediately as the previous time, I noticed that I'm back to the misaligned button :-(
