### ISSUE TITLE
Windows confirmation dialog blocked by Open-Shell Menu

### ISSUE THREAD

**Issue by Gittyperson** [Open-Shell/Open-Shell-Menu#257]
1. In the Windows Recycle Bin Properties, enable "Display delete confirmation dialog".
2. Use a style that can open a big enough Start Menu to cover a large part of the screen. For example, expand a few folders within Programs using the "Classic with two columns" style.
3. Right-click an entry from the Start Menu (e.g a program uninstall shortcut), and select 'Delete'.
4. The delete confirmation dialog opens but if the Start Menu is covering it, the dialog will not become visible and cannot be accessed. Neither Yes/No can be selected. You can only close/cancel the dialog via Alt-Tab.
5. The Start Menu will not close, unless the dialog has been closed.

In the screenshot, I've pressed Alt-Tab and you can see the Delete confirmation dialog is open. But it is not visible/accessible, because the Start Menu is on top, even if selected with Alt-Tab.

Open-Shell Menu 4.4.142, Windows 10 Pro x64 1909 18363.476

![Prompt blocked](https://user-images.githubusercontent.com/7165208/69327754-b1ec5e00-0c56-11ea-9120-913dba1371d5.png)

**Comment by stringydave** [comment]
When doing the same operation in Classic Shell, the menu is closed before the dialogue is produced by Windows, so you can see the dialogue & action it.
In Open Shell the menu remains open, and on top, and the dialogue is produced behind it.  It is possible to Alt+Tab to the dialogue window.  Whilst you've got Alt+Tab pressed, you can see which key you need to press (in the screenshot above it would be Alt+Y), then release and press the required key combination.  Of course if that produces another dialogue box you'll have to do it all again.
I got tired of this and I have just reverted back to Classic Shell

**Comment by Gittyperson** [comment]
Open-Shell always worked like Classic Shell too, but for some reason the change was implemented in the previous update to accommodate a single user request. This is completely non-standard Windows behaviour. A pity, really.

Come on guys, please make this "always on top" thing at least optional.

**Comment by ge0rdi** [comment]
@Gittyperson 
@stringydave 
Could you please test with this [build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/30204242/artifacts)?
It should fix the issue.

**Comment by Gittyperson** [comment]
It fixes it, thank you. Perhaps you could also consider making [this](https://github.com/Open-Shell/Open-Shell-Menu/issues/238) optional, although it's not causing problems any more.

**Comment by ge0rdi** [comment]
@Gittyperson 
Thanks for confirmation and suggestion too.
For now I'd leave it as it is. If there will be more people who don't want this behavior we can consider making it optional.

**Comment by scooby1** [comment]
Observation with update 4.4.143
Whilst fix in 4.4.143 works OK for the "Dialog Box" the ensuing Progress Windows that opens still appears BENEATH the Open-Shell Menus

**Comment by Gaurav-Original-ClassicShellTester** [comment]
I seem to remember that Ivo made the menu close behavior default because he could not figure out a way to make certain shell extension dialogs or this delete confirmation UAC dialog for All Users menu appear in front of the Start menu. But ge0rdi seems to have fixed that. I just tested it extensively and even if the menu doesn't close, all context menu commands which produce a dialog seem to be appear on top of the menu, so no dialog is blocked as such.
